### ISSUE TITLE
Execute ./setup.sh  Line 54 Password required

### ISSUE THREAD

**Issue by Pure-cai** [oldkingcone/slopShell#10]
I have installed postgresql ，Execute ./setup.sh  ,print Line 54 Password required，Where is this password?
![image](https://user-images.githubusercontent.com/59380674/148786473-ed4e3bdc-fbe3-494f-b24a-3fbcbc4bbc60.png)

**Comment by oldkingcone** [comment]
close with git commit:
https://github.com/oldkingcone/slopShell/commit/5967ee0c60a8cb3a86faebf1ec3308484fb82530
