### ISSUE TITLE
Please run as root

### ISSUE THREAD

**Issue by xixixiba** [oldkingcone/slopShell#9]
![1641361909(1)](https://user-images.githubusercontent.com/95956613/148337506-ad50a300-b81e-4ee4-bdb2-86b7ba060426.jpg)
![1641361960(1)](https://user-images.githubusercontent.com/95956613/148337511-e3c31d61-b0b2-4be4-ae32-47662e9417fc.jpg)
The root user is still prompted to run as the root user???

**Comment by oldkingcone** [comment]
You have to call the script with sudo:
![image](https://user-images.githubusercontent.com/11233163/148386892-da904be9-1b94-4472-8f07-092db94114f9.png)
